### ISSUE TITLE
APIs need a link from the main site.

### ISSUE THREAD

**Issue by rossjones** [datagovuk/apiserver#21]
some links from data.gov.uk datasets to the APIs

**Comment by rossjones** [comment]
Add a resource where format = API.  We can use this to build a facet (including existing).

**Comment by rossjones** [comment]
This should ideally be done by ETL, will add another ticket, but for now let's shortcut it as we don't have many.

**Comment by rossjones** [comment]
Adding another resource with format of API, after doing it, feels wrong.  The API resource has
- format lower cased 
- a likely bad QA because it is HTML
- no preview
- no obvious way of accessing the API.

How do we feel about an extra on the package that contains a URL.  We can facet on that and display it differently on both the package/read and package/search pages?

**Comment by davidread** [comment]
Yes it feels a bit wrong, but I'd rather fix this for all dataset APIs
rather than just your ones.

I think it needs to be a resource, because that is the CKAN meaning of 'a
link to data'. That's how core CKAN does APIs too. It links up with the
DCAT mapping too.
- Your web page would have title "API demo" and be an additional resource
  with format=HTML. It certainly isn't the API itself!
- The actual API URL e.g.
  https://test.data.gov.uk/data/api/service/health/hospitals can be a data
  resource with format=API Clearly that's not very useful on it's own, but if
  you know how to use these style APIs then it is. In a similar way, there is
  a convention that CKANs have their API at http://domain.com/api but plenty
  of CKANs have it elsewhere e.g. because they have a drupal front-end or
  mount ckan at a sub-url. It is therefore quite helpful to know the base URL
  of an API, even if calling it doesn't do much.

**Comment by rossjones** [comment]
Should make sure api is upper case for the format.

Should rename Download to something else ... Link to API 

Should remove cached button.

Look at API as a facet.

**Comment by rossjones** [comment]
CSV 

```
dataset,description,url
naptan,"Access to ferry port information",https://test.data.gov.uk/data/api/transport
naptan,"Access to train station information",https://test.data.gov.uk/data/api/transport
```

**Comment by rossjones** [comment]
Links and facets now on prod2.  Must not forget to add api to the search-facet list in ckan.ini on deploy.  

Can be deployed anytime before the API is up and running,.

**Comment by davidread** [comment]
This is great, please do deploy
