### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by wood-chris** [datagovuk/apiserver#64]
The blog post about school data (https://data.gov.uk/blog/guest-post-developers-guide-linked-data-apis-jeni-tennison) is a pretty good tutorial, but the education api doesn't seem to exist any more, so it's not possible to test everything / play around with the queries.  Can the tutorial be updated with a dataset that is still available?!

(as an aside, I also followed a href link that was to http://data.gov.uk/interact - this returns a 404; I've just realised all the other menu links from the top bar go to a real page)

**Comment by davidread** [comment]
Sorry, government interest has moved on from the material in this blog post, I'm afraid.

**Comment by rossjones** [comment]
@wood-chris Just to clarify, the blog post was from 2010 and the service has since moved off our site.  Apparently the Sparql endpoint is now available at http://education.data.gov.uk/sparql/education/query.html 

It isn't really related to the current API work though (or this repository), and I don't forsee us providing an API for that data in the near future.

**Comment by wood-chris** [comment]
I noticed it was a pretty old blog post - but it is still very useful for new-comers to linked data.  Thanks the for the reply tho
